### PR TITLE
Added TicTacToe!

### PR DESCRIPTION
**Pull request by Nishanth4**
I added TicTacToe, this is my first time contributing, hopefully I did everything correctly! Thank you!

### CODE REVIEW

**Comment by daviscodesbugs** [comment]
Thanks for contributing! This is pretty close, with JSON, objects need to be separated with commas.
In this case, add a comma at the end of line 9, and the end of line 12. Consider putting it in the [formatter on this site](https://jsonformatter.curiousconcept.com/).

Just make the change on your fork, and push to your repo, GitHub will update this pull request.

**Comment by Nishanth4** [comment]
Thank you so much for being so supportive! I think I fixed the issue!

**Comment by daviscodesbugs** [comment]
Sure thing; GitHub can be quite a beast to deal with, and it just makes it worse if collaborators are rough.

You're code looks good and pasts the unit tests :+1: 

There's a couple minor things (for consistency). But I'll merge your PR and fix it myself.
Merging.

**Comment by daviscodesbugs** [comment]
Your change is all added in. Great work, and feel free to contribute again!

**Comment by Nishanth4** [comment]
Thank you very much!

**Pull request merged**
