### PR TITLE
Add Sorry

### PR DESCRIPTION
**Pull request by staticwave**
Referencing #1 

Add Sorry json and pdf

### CODE REVIEW

**Comment by daviscodesbugs** [comment]
Your rulebook PDF file has an all cap file extension. If you make it lowercase, it should pass the tests and be clear for merge.

**Comment by staticwave** [comment]
Whoops, must have left caps lock on. I'll fix it, thanks.



-------- Original message --------

**Comment by staticwave** [comment]
@daviscodesbugs My file system is showing a lowercase extension now, but when I pushed the initial change the file still showed as uppercase. I've removed the rulebook for now and will try again later.

**Comment by daviscodesbugs** [comment]
Okay, sounds good. The JSON looks great, so I'll merge it in!

**Pull request merged**
