### PR TITLE
Add operation.json

### PR DESCRIPTION
**Pull request by SMaguina**

### CODE REVIEW

**Comment by daviscodesbugs** [comment]
Not super familiar with operation, is "doctor cards" only one card, or a deck?

**Comment by SMaguina** [comment]
It's a deck of cards (24 to be exact). Do you want that included as 24 counts?

**Comment by daviscodesbugs** [comment]
If you could make it `"total_count": 24` and then separate it out by cards.
The idea is that I could get my operation game and figure out what cards I'm missing from my game.

**Comment by SMaguina** [comment]
It's a fun game! I have updated the .json file to include the card names and count for each. The cards direct the player to which ailment to cure.

**Comment by daviscodesbugs** [comment]
Looks good, I'll merge it in as is and close this PR.
If you'd like to expand out "play money" as well, I'd appreciate it!
Good work 👌 Merging

**Pull request merged**
