### PR TITLE
Adding Reversi #1

### PR DESCRIPTION
**Pull request by charlottetan**
This game was first invented in 1883 by a couple of Englishmen!

### CODE REVIEW

**Comment by charlottetan** [comment]
gyah its not in a folder. sec

**Comment by daviscodesbugs** [comment]
This looks great!
However, isn't the idea with reversi that the pieces have black on one side and white on the other so that you "reverse" the pieces when "captured"? Perhaps on the piece list we just list the 64 pieces.

Also, let's mark it as Othello (as marketed by Mattel) and add Reversi as the alternate name. That way we can add the `publisher` attribute and include [this rulebook](http://service.mattel.com/instruction_sheets/52551.pdf).

**Comment by charlottetan** [comment]
Good points! I'll do that, sec

**Comment by daviscodesbugs** [comment]
Magnificent work. Thank you for this! :100: 
Merging.

**Pull request merged**
