### PR TITLE
Add Uno

### PR DESCRIPTION
**Pull request by matankb**

### CODE REVIEW

**Comment by daviscodesbugs** [comment]
Looking good! 👍 just a few small things:
name still says "Settlers of Catan"
break down cards by color (in addition to value)

**Comment by matankb** [comment]
Will do!

**Comment by daviscodesbugs** [comment]
Looking way good - one more request 😬  
Break down number cards into respective values - the idea here is that if I lost a card, I would know what I'm missing. I have 19 red number cards... are they all 7s? are they numbers 1-19?
Perhaps add attribute `"values": [1,1,1,1,2,2,3,3,4,6,6]`
or `{"value":1,"count",4},{"value":2,"count":2}`

**Comment by daviscodesbugs** [comment]
Beautiful 👌
Thanks for contributing! Merging.

**Pull request merged**
