### PR TITLE
Added POOP: The Game

### PR DESCRIPTION
**Pull request by Zenith-One**
Very fun game for all ages. It sounds completely juvenile because it is, but it's hilarious fun.

Check out http://poopthegame.com/ if interested.

Note: There is no rulebook in PDF form that I could find, as the rules are printed on the front and back of one of the cards in the box, along with 3 other cards with variants. Instead, I listed the rule cards at the top. Not 100% sure on the data structure of the rule cards though. Let me know what you think.

### CODE REVIEW

**Comment by Zenith-One** [comment]
I think Travis might be stalled.

**Comment by daviscodesbugs** [comment]
I opened this issue last night and woke up to about 20 new PRs. I'm just on the free tier, so between checking each commit on each PR, and then checking each merged PR, it's just backed up.

I think the rulecards in the JSON is just fine.

This looks like a hilarious game; I might have to request it for Christmas!

**Comment by daviscodesbugs** [comment]
There we go. Looks good - Merging.

**Comment by Zenith-One** [comment]
There's a package with the original game and a 6-10 player expansion called
POOP In a Bag which is what I got

**Comment by Zenith-One** [comment]
It was about $20 and we've gotten a lot of enjoyment out of it. Highly
recommend it.

**Pull request merged**
