### PR TITLE
Add linting to game json files

### PR DESCRIPTION
**Pull request by wachunga**
With so many contributors, style is getting very inconsistent (eg tabs instead of 4 spaces). I added `npm run lint` to resolve this. I'll leave it up to you whether you want this to run along with `npm test` but I would recommend doing so.

This required changing the jsonlint library to a more popular one that has more features.

### CODE REVIEW

**Comment by daviscodesbugs** [comment]
This is something that I've been meaning to tackle, but have been moderately overwhelmed with the recent response to the project.

This PR looks good. :+1: 
Just for clarification, running `npm run lint` lints _all_ json files in project. Correct?
Then does the change in unit test ensure that the files mirror what it should when linted?

**Comment by wachunga** [comment]
`npm run lint` lints all json files in the game directory. If there were json files elsewhere, they wouldn't be linted currently.

The unit tests operate exactly the same as before. The only changes I made were to DRY them up a little and replace the json-lint dep with the jsonlint one. I tested to ensure that the new version fails as expected if there's a syntax error.

**Comment by daviscodesbugs** [comment]
Okay, that's great. I'd only want to list json in games.

I noticed that, I just wasn't sure if the new lint test would fail if the file wasn't correctly linted already (e.g. the file was tabbed rather than 4-spaced).

**Comment by wachunga** [comment]
Oh, I understand now. No, it won't fail for stylistic issues. But if you change `scripts.text` to be `./lint.sh; mocha` then they'll always get fixed anyway instead of the build breaking and requiring an extra commit.

**Comment by daviscodesbugs** [comment]
However, they won't be committed to the repo as linted, unless the user runs the `test` target before they submit their PR, correct? I think that's the primary issue with PRs is the inattention to formatting and other contribution specs.

I'm unaware of a way to have Travis lint and commit as part of it's build process; Do you know of one?

**Pull request merged**
