### PR TITLE
Added rulebook for playing-cards and mastermind

### PR DESCRIPTION
**Pull request by amiteshP**

### CODE REVIEW

**Comment by daviscodesbugs** [comment]
These look great! :+1: 
Could you switch out the mastermind rules for [this file](http://www.pressmantoy.com/game-rules/Ultimate%20Mastermind%20Rules%20%281%29.pdf) since this one is from the board game manufacturer?

**Comment by amiteshP** [comment]
Sure, i'll pull out a new request! :)

**Comment by amiteshP** [comment]
@daviscodesbugs is it fine now?

**Comment by daviscodesbugs** [comment]
I merged in something else that now causes conflicts. Could you rename the file and line in JSON to "rulebook-ultimate-mastermind.pdf"? Sorry for the trouble.

**Comment by amiteshP** [comment]
no problem! I guess now it'll fine :)

**Comment by daviscodesbugs** [comment]
Alrighty, I merged you changes; everything looks great. Thank you! 🤘

**Comment by amiteshP** [comment]
Hey! It was great contributing! Thank"you" B|

**Pull request merged**
